# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8f4cd1398d47c8b047c4f7825b08ac5223ed7571e090a66409d25f1f5e48453db6be448f7a3fa8602b70201c39bdad4bd6b4f459c0b7d4aaf81bb230ef8d9618

test:
  secret_key_base: 46daf99c6b50e2e723444bb4849ace446d7382a9f7e056eea905f6cf487440ac742d11ca834b8369942bbb67e9403211345fc6624d9bdb684921c9f93e2d942c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
